substitutions:
  name: "espa-mini-v1"
  friendly_name: "eSPA Mini v1"
  project_name: "jbergler.esphome-spanet"
  project_version: "0.1.0"

  spa_uart_tx_pin: GPIO15
  spa_uart_rx_pin: GPIO16
  spa_uart_baud: "38400"

  fallback_ap_password: "12345678"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

packages:
  base: !include espa-mini-base.yaml

output:
  - platform: gpio
    id: status_led_1
    pin: GPIO14
  - platform: gpio
    id: status_led_2
    pin: GPIO41
  - platform: gpio
    id: status_led_3
    pin: GPIO42
  # GPIO43 omitted: conflicts with USB on ESP32-S3

spanet:
  id: spa_hub
  status:
    leds:
      - status_led_1
      - status_led_2
      - status_led_3
