substitutions:
  name: "espa-mini-v2"
  friendly_name: "eSPA Mini v2"
  project_name: "jbergler.esphome-spanet"
  project_version: "0.1.0"

  spa_uart_tx_pin: GPIO20
  spa_uart_rx_pin: GPIO19
  spa_uart_baud: "38400"

  fallback_ap_password: "12345678"

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf

packages:
  base: !include espa-mini-base.yaml

light:
  - platform: esp32_rmt_led_strip
    id: status_rgb
    pin: GPIO10
    num_leds: 1
    chipset: WS2812
    rgb_order: GRB
    internal: true

spanet:
  id: spa_hub
  status:
    rgb_light: status_rgb
