# PlatformIO configuration for local unit tests

[platformio]
default_envs = cpp-test
test_dir = tests

[env:cpp-test]
platform = native
build_type = debug
build_flags = -std=c++17 -I components/spanet
test_framework = googletest
test_filter =
	test_spanet_component
	test_spanet_parser
	test_uart_rx
	test_spanet_state
	test_update_debounce
test_build_src = yes
build_src_filter = +<../components/spanet/>

