# PlatformIO configuration for local unit tests

[platformio]
default_envs = cpp-test, test_controller_status
test_dir = tests

[env:cpp-test]
platform = native
build_type = debug
build_flags = -std=c++17
test_framework = googletest
test_filter = test_spanet_parser test_uart_rx

[env:test_controller_status]
platform = native
build_type = debug
build_flags = -std=c++17
test_framework = googletest
test_filter = test_controller_status
