# PlatformIO configuration for local unit tests

[platformio]
default_envs = cpp-test, test_spanet_state
test_dir = tests

[env:cpp-test]
platform = native
build_type = debug
build_flags = -std=c++17
test_framework = googletest
test_filter =
	test_spanet_parser
	test_uart_rx

[env:test_spanet_state]
platform = native
build_type = debug
build_flags = -std=c++17
test_framework = googletest
test_filter = test_spanet_state
